using Gtk;
using WebKit;
int main(string[] argv){
var app = new Gtk.Application("com.appont.com", GLib.ApplicationFlags.DEFAULT_FLAGS);
app.activate.connect(() => {
var win1 = new ApplicationWindow(app);
var closd = new Window(); closd.set_title("Sei sicuro di voler chiudere Appont?"); var closdbox = new Box(VERTICAL, 3);
closd.set_modal(true); closd.default_width = 300;
var closdno = new Button.with_label("No"); closdno.clicked.connect(() =>{closd.set_visible(false);});
var closdyes = new Button.with_label("Si"); closdyes.clicked.connect(() =>{win1.destroy();});
var wintxtload = new Window(); var loadalog = new FileDialog(); loadalog.set_title("Apri file .txt"); // wintxtload.set_child(loadalog);
var wintxtsave = new Window(); var savealog = new FileDialog(); savealog.set_title("Salva file come .txt"); // wintxtsave.set_child(savealog);
var scrl = new ScrolledWindow();
var box = new Box(VERTICAL, 0);
var web = new WebView();
var buffa = new TextBuffer(null); var text = new TextView.with_buffer(buffa);
var buffed = new EntryBuffer();
var menupop = new Popover();
var menubtn = new MenuButton();
var selfile = new CheckButton.with_label("file://");
var selhttps = new CheckButton.with_label("https://");
var selhttp = new CheckButton.with_label("http://");
var selnothing = new CheckButton.with_label("Nessun Prefisso"); selnothing.set_active(true); selfile.set_group(selnothing); selhttps.set_group(selnothing); selhttp.set_group(selnothing);
var linkentry = new Text.with_buffer(buffed); linkentry.set_hexpand(true);
var bback = new Button.with_label("←"); bback.clicked.connect(() => {web.go_back();});
var bforward = new Button.with_label("→"); bforward.clicked.connect(() => {web.go_forward();});
var breload = new Button.with_label("↺"); breload.clicked.connect(() => {web.reload();});
var bsave = new Button.with_label("Carica Appunti");
bsave.clicked.connect(() => {loadalog.open.begin(wintxtload, null, (obj, res) =>{
var flnm = loadalog.open.end(res); uint8[] contents;
flnm.load_contents(null, out contents, null);
text.buffer.text = (string) contents;});});
var bload = new Button.with_label("Salva Appunti");
bload.clicked.connect(() => {savealog.save.begin(wintxtsave, null, (obj, res) =>{
TextIter bget1; TextIter bget2;
buffa.get_start_iter(out bget1); buffa.get_end_iter(out bget2);
var grab = buffa.get_text(bget1, bget2, true);
var flnm2 = savealog.save.end(res);
var ph = flnm2.get_path(); FileUtils.set_contents(ph, grab);
flnm2.new_for_path(ph);});});
var linkbtn = new Button.with_label("Vai");
linkbtn.clicked.connect(() => {linkentry.get_buffer();
var texto = buffed.get_text();
selfile.get_active();
if (selnothing.get_active() == true){web.load_uri(texto);};
if (selfile.get_active() == true){web.load_uri("file://" + texto);};
if (selhttps.get_active() == true){web.load_uri("https://" + texto);};
if (selhttp.get_active() == true){web.load_uri("http://" + texto);};});
var panel = new Paned(HORIZONTAL);
var scuff = new Box(HORIZONTAL, 0);
var menubox = new Box(HORIZONTAL, 0);
web.set_size_request(250, 250);
scrl.set_child(text);
scrl.set_size_request(250, 250);
var sets = new WebKit.Settings();
sets.auto_load_images = true;
sets.enable_javascript = true;
sets.allow_universal_access_from_file_urls = true;
sets.allow_file_access_from_file_urls = true;
sets.allow_modal_dialogs = true;
sets.enable_media = true;
sets.enable_media_capabilities = true;
sets.enable_webgl = true;
sets.enable_mediasource = true;
sets.enable_webaudio = true;
sets.enable_encrypted_media = true;
sets.enable_webrtc = true;
web.set_settings(sets);
web.load_uri("https://www.duckduckgo.com");
web.set_hexpand(true); web.set_vexpand(true);
scrl.set_hexpand(true); scrl.set_vexpand(true);
panel.set_start_child(scrl);
panel.set_end_child(web);
menupop.set_child(menubox);
menubox.append(selnothing);
menubox.append(selfile);
menubox.append(selhttps);
menubox.append(selhttp);
menubtn.set_popover(menupop);
closdbox.append(closdno);
closdbox.append(closdyes);
box.append(scuff);
scuff.append(bsave);
scuff.append(bload);
scuff.append(menubtn);
scuff.append(linkentry);
scuff.append(linkbtn);
scuff.append(bback);
scuff.append(bforward);
scuff.append(breload);
box.append(panel);
win1.title = "Appont";
win1.default_height = 550;
win1.default_width = 500;
win1.set_child(box);
closd.set_child(closdbox);
win1.present();
win1.close_request.connect(() =>{closd.set_visible(true); return true;});});
return app.run(argv);}
